"""made unique food_list_id

Revision ID: 1f47819c846e
Revises: f10b46f6b498
Create Date: 2024-01-02 21:55:46.170745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f47819c846e'
down_revision: Union[str, None] = 'f10b46f6b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'breakfast_lists', ['food_list_id'])
    op.create_unique_constraint(None, 'dinner_lists', ['food_list_id'])
    op.create_unique_constraint(None, 'lunch_lists', ['food_list_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lunch_lists', type_='unique')
    op.drop_constraint(None, 'dinner_lists', type_='unique')
    op.drop_constraint(None, 'breakfast_lists', type_='unique')
    # ### end Alembic commands ###
