"""Updated db2

Revision ID: ab1f3fcd6f32
Revises: 
Create Date: 2023-12-30 15:12:31.517108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1f3fcd6f32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakfast_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakfast_lists_id'), 'breakfast_lists', ['id'], unique=False)
    op.create_table('dinner_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dinner_lists_id'), 'dinner_lists', ['id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.String(length=5), nullable=False),
    sa.Column('fats', sa.String(length=5), nullable=False),
    sa.Column('proteins', sa.String(length=5), nullable=False),
    sa.Column('carbohydrates', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_table('lunch_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lunch_lists_id'), 'lunch_lists', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('breakfast_food_association',
    sa.Column('breakfast_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['breakfast_id'], ['breakfast_lists.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], )
    )
    op.create_table('dinner_food_association',
    sa.Column('dinner_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dinner_id'], ['dinner_lists.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], )
    )
    op.create_table('food_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.Integer(), nullable=True),
    sa.Column('lunch', sa.Integer(), nullable=True),
    sa.Column('dinner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('valid_to', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['breakfast'], ['breakfast_lists.id'], ),
    sa.ForeignKeyConstraint(['dinner'], ['dinner_lists.id'], ),
    sa.ForeignKeyConstraint(['lunch'], ['lunch_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_lists_id'), 'food_lists', ['id'], unique=False)
    op.create_table('lunch_food_association',
    sa.Column('lunch_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['lunch_id'], ['lunch_lists.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lunch_food_association')
    op.drop_index(op.f('ix_food_lists_id'), table_name='food_lists')
    op.drop_table('food_lists')
    op.drop_table('dinner_food_association')
    op.drop_table('breakfast_food_association')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lunch_lists_id'), table_name='lunch_lists')
    op.drop_table('lunch_lists')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_dinner_lists_id'), table_name='dinner_lists')
    op.drop_table('dinner_lists')
    op.drop_index(op.f('ix_breakfast_lists_id'), table_name='breakfast_lists')
    op.drop_table('breakfast_lists')
    # ### end Alembic commands ###
