"""oneToone between foodlist and meals

Revision ID: f10b46f6b498
Revises: 190b1f59ca59
Create Date: 2024-01-02 21:42:32.712625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10b46f6b498'
down_revision: Union[str, None] = '190b1f59ca59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
